#ifndef _SERRORDEF_H
#define _SERRORDEF_H

#define ERR_SOCKET_EXCEPTION 100
#define ERR_VALIDATE_HEAD 101
#define ERR_SYS_ERROR 102
#define ERR_OPERATOR_DENY 103
#define ERR_CMDERR 104
#define ERR_FEAD_FILE_EOF 105
#define ERR_AUTH_ERR 106
#define ERR_USER_HAS_EXISTED 107
#define ERR_UNAME_OR_PSD_ERROR 108

#endif